# Generated by Django 4.1.1 on 2022-10-13 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sku',
        ),
    ]
