# Generated by Django 4.1.1 on 2022-10-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_inventory_description_remove_inventory_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='fullname',
            field=models.CharField(default='', editable=False, max_length=30),
        ),
    ]
