# Generated by Django 4.1.1 on 2022-10-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inventory_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='address',
            field=models.CharField(default='', editable=False, max_length=30),
        ),
    ]
