# Generated by Django 4.1.1 on 2022-10-13 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_inventory_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='title',
        ),
    ]
