# Generated by Django 4.1.1 on 2022-10-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_inventory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='fullname',
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
