# Generated by Django 4.1.1 on 2022-10-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_inventory_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='fullname',
            field=models.CharField(max_length=30),
        ),
    ]
