# Generated by Django 4.1.1 on 2022-11-19 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_try'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Try',
        ),
    ]
