# Generated by Django 4.1.1 on 2022-11-19 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_try'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Try',
            new_name='Product',
        ),
    ]
