# Generated by Django 4.1.1 on 2022-11-26 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_try_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='address',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='fullname',
            new_name='names',
        ),
    ]
