# Generated by Django 4.1.1 on 2023-11-19 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderitem_product_id_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
    ]
